name: Log Info
description: Logs info about the workflow or action, and all its inputs.
inputs:
  inputs_object:
    description: The inputs object from the calling workflow or action, wrapped in `toJSON()`.
    required: false
    default: '{}'
  caller:
    description: What called this action (workflow or another action)
    required: false
    default: workflow
runs:
  using: 'composite'
  steps:
    - name: Workflow Information
      shell: bash
      run: >-
        if [[ "${{ inputs.caller }}" == "workflow" ]]; then
          echo "----------------------"
          echo "Workflow Information:"
          echo "----------------------"
          echo "Workflow trigger event: ${{ github.event_name }}"
          echo "Event action: ${{ github.event.action }}"
          echo "Event label: ${{ github.event.label.name }}"
          echo "PR base ref: ${{ github.event.pull_request.base.ref }}"
          echo "PR head ref: ${{ github.event.pull_request.head.ref }}"
          echo "PR labels: ${{ toJSON(github.event.pull_request.labels.*.name) }}"
          echo "Ref: ${{ github.ref }}"
          echo "Base ref: ${{ github.base_ref }}"
          echo "Ref name: ${{ github.ref_name }}"
          echo "Runner name: ${{ runner.name }}"
          echo "Runner env: ${{ runner.environment }}"
          echo "Runner OS: ${{ runner.os }}"
        fi

        echo "----------------------"
        echo "Inputs:"
        echo "----------------------"
        echo "${{ inputs.inputs_object }}"
        echo "----------------------"
