# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: print 1
        run: |
          # Define the Bash array
          bash_array=("element1" "element2" "element3")
          
          # Convert the Bash array to a JSON array using jq
          json_array=$(printf '%s\n' "${bash_array[@]}" | jq -R . | jq -s .)

          echo "Bash Array: [${bash_array[*]}]"
          echo "JSON Array: $json_array"

      - name: print 2
        run: |
          # Define the Bash array
          bash_array=()
          
          # Convert the Bash array to a JSON array using jq
          json_array=$(printf '%s\n' "${bash_array[@]}" | jq -R . | jq -s .)

          echo "Bash Array: [${bash_array[*]}]"
          echo "JSON Array: $json_array"

