# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  a:
    runs-on: ubuntu-latest
    if: ${{ '1' == '2' }}
    steps:
      - name: print
        run: echo "job a"
  b:
    needs: [a]
    if: needs.check-code-style.result != 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "job b"
  c:
    needs: [b]
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "job c"

