name: Reuser

on:
  workflow_dispatch:
  push:

jobs:
  job1:
    uses: ./.github/workflows/workflow1.yml
    strategy:
      matrix:
        i3: [true, false]
    with:
      i1: this is i1 from reuser
      i2: this is i2 from reuser
      i3: ${{matrix.i3}}