name: Workflow1

on:
  workflow_call:
    inputs:
      i1:
        description: input1
        type: string
        required: false
        default: input1default
      i2:
        description: input2
        type: string
        required: false
      i3:
        description: a boolean
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      i1:
        description: input1
        required: false
        default: input1default
      i2:
        description: input2
        required: false
      i3:
        description: a boolean
        required: false
        default: false
  # push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Workflow Information
        uses: ./.github/actions/log-info
        with:
          inputs_object: ${{ toJSON(inputs) }}

      - name: test if statement
        run: |
          shopt -s nocasematch
          if [[ ${{ inputs.i1 }} == "pro"* ]]; then
            echo "starts with pro"
          else
            echo "does not start with pro"
          fi

      # - name: boolean object is truly
      #   if: ${{ inputs.i3 }}
      #   run: echo "hi"

      # - name: oolean string is true
      #   if: ${{ inputs.i3 == 'true'}}
      #   run: echo "hi"

      # - name: boolean is true
      #   if: ${{ inputs.i3 == true}}
      #   run: echo "hi"

      # - name: boolean is falsy
      #   if: ${{ !inputs.i3 }}
      #   run: echo "hi"

      # - name: boolean string is false
      #   if: ${{ inputs.i3 == 'false' }}
      #   run: echo "hi"

      # - name: boolean is false
      #   if: ${{ inputs.i3 == false }}
      #   run: echo "hi"
