name: Workflow1

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      i1:
        description: input1
        required: false
        default: input1default
      i2:
        description: input2
        required: false
  # push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Workflow Information
        uses: ./.github/actions/log-info
        with:
          inputs_object: ${{ toJSON(github.event.inputs) }}
